org: hamzak99
app: my-serverless-compose
service: aws-node-http-api-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  producer:
    handler: handler.producer
    events:
      - httpApi:
          method: GET
          path: /
